version: "3"

services:
  app:
    container_name: appbank
    build: .
    ports:
      - "50052:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: always
    ports: 
      - 5432:5432
    environment:
     POSTGRES_USER: pguser
     POSTGRES_PASSWORD: pgpass